### ISSUE TITLE
unblurs on scrolling chat section

### ISSUE THREAD

**Issue by Sarahkhan20** [tusharnankani/blurrit#11]
it maybe because on hovering it unblurs, but what if I want to scroll down and not let anyone see the chats

**Comment by tusharnankani** [comment]
Hey Sarah, thank you for opening the issues!
I appreciate making discussions public :D

> but what if I want to scroll down and not let anyone see the chats

So, this is a feature and we might not be able to do anything about this. Reason being — Users would want to know where they are scrolling to. You might know where you want to scroll to, but would people know where to click? 
That's why, temporarily unblurring on hover would do less harm than "not let anyone see the chats".

I hope that made sense, let me know if you need any clarifications?

**Comment by Sarahkhan20** [comment]
Yeah this definitely makes sense to me. Although I feel Here again the
privacy becomes an issue. Right now, other than this I don't have any idea.
But definitely we should keep it the way it is.
